### ISSUE TITLE
How to test the SwingingDoor algorithm?

### ISSUE THREAD

**Issue by Katobaa** [gfoidl/DataCompression#35]
Hello Günther!

Gostaria de fazer uma pergunta... Como eu faço para testar esse algoritmo de SwingingDoor?  Você poderia por gentileza fazer um tutorial?

Thank you!

**Comment by gfoidl** [comment]
@Katobaa can you work with the [demos](https://github.com/gfoidl/DataCompression/tree/master/demos)? What especially do you need, to understand how to use it?

**Comment by Katobaa** [comment]
Hi Günther!

I would like to take a mass of data from a tag and go through the compression. How do I do this using your solution?

Could you pass your email?

Thank's

**Comment by gfoidl** [comment]
Let's turn it around :wink: Can you provide sample data, then I'll add a demo for this.

Basically it is https://github.com/gfoidl/DataCompression/blob/2785a5a43290758274ce99da56a873a91f6813d4/demos/gfoidl.DataCompression.Demos.SwingingDoor/Program.cs#L14-L20

**Comment by Katobaa** [comment]
The parameter "1.5" was the compression factor?

**Comment by gfoidl** [comment]
It's the _compression deviation_ https://github.com/gfoidl/DataCompression/blob/2785a5a43290758274ce99da56a873a91f6813d4/source/gfoidl.DataCompression/ExtensionMethods.cs#L69-L72 (see also the [description](https://github.com/gfoidl/DataCompression/blob/master/doc/SwingingDoor.md)).

**Comment by gfoidl** [comment]
Closing, as inactive.
