### ISSUE TITLE
Algorithm does not return correct compressed data sample

### ISSUE THREAD

**Issue by FloCD** [gfoidl/DataCompression#70]
Hello gfoidl,

I have tested your algorithm again with the following test sample (<seconds>, <value>) and tolerance = 2:

```
1, 0
2, 1
3, 2
4, 5
5, -2
6, 5
7, 4
8, 3
9, 5
```

As far as I have understood the algorithm, the following sample should be the result:

```
1, 0
4, 5
5, -2
6, 5
8, 3
9, 5
```

Could you maybe test that on your side? Or is my assumption wrong? I have used your swinging door demo code and adapted the tolerance.

All the best

FloCD

**Comment by gfoidl** [comment]
Thanks for validating.

Edit: the rest of this comment is wrong! Please ignore.

~When I construct / reply the algorithm by hand (on paper with pencil and ruler), the expected data should be~
```diff
1, 0
4, 5
5, -2
6, 5
-8, 3
+7, 4
9, 5
```

~Let's focus on what (should) happen at (5, -2).~
1. ~(5, -2) lies outside the door from previous point -> archive~
2. ~new door is opened from (4, 5) to (5, -2)~
3. ~(6, 5) lies outside that door -> archive, so {(5, -2), (6, 5)} are archived now~
4. ~new door is opened from (5, -2) to (6, 5)~
5. ~(7, 4) lies outside that door -> archive, so {(5, -2), (6, 5), (7, 4)} are archived now~
6. ~new door is opened from (6, 5) to (7, 4)~
7. ~(8, 3) lies inside that door -> not archived~
8. ~(9, 5) is the last point -> archive, so {(5, -2), (6, 5), (7, 4), (9, 5)} are archived now~

---

Anyway there's still a bug in the implemented algorithm (damned).
All depends on the test-data 🙈

**Comment by FloCD** [comment]
Hi,

why should we discard the second to last point "3"? (it's a more "interesting" ;) point as "4" because it's a extreme point) So I think we have to discard the value 4 because this can be represented via the points 5 and 3 (step 7).

All the best

FloCD

**Comment by gfoidl** [comment]
I'd also expect (8, 3) to be in the results, as local minima. But with tolerance 2 it's within the door from (7, 4) to (9, 5). So in that case the tolerance should be lowered to have this minima.

Is my description of the steps above correct?

I don't believe it's correct to just store the penultimate datapoint, and the last datapoint. In available literature I didn't find hint on how to handle the end of the sequence correctly.

Let's stick by the tolerance of 2 for a moment: to have (8, 3) in the results how would one handle that case efficiently by the algorithm? I have no clue at the moment withou the need to buffer the datapoints (when given as `IEnumerable<DataPoint>`).

**Comment by FloCD** [comment]
Hi again,

I also would not in general store the penultimate and the last datapoint, but I would store the last datapoint in any case. My implementation is, depending if the "current" value is in the swinging door area:

- if it is in the area: => recalculate the swinging doors slopes with the current value and delete previous value
- if it is not in the area: => create a new swinging door with the previous value and the current value

(Given that the first two values are already used for constructing the first swinging door.)

**Comment by gfoidl** [comment]
@FloCD you are / were right with the expected data 👍🏻 
Please don't blame for me for the fault of my wrong construction before (don't know what came in my mind with the (7, 4)) 😉 

Thank you very much for catching this, and for providing sample data!

PR https://github.com/gfoidl/DataCompression/pull/72 fixes that. Can you please give it a try?
